services:
  mysql-db:
    container_name: codegram-db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - codegram-net
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  
  express-app:
    container_name: codegram-express
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - codegram-net
    depends_on:
      - mysql-db

  nextjs-app:
    container_name: codegram-next
    build: 
      context: ./frontend/codegram
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - codegram-net
    depends_on:
      - express-app

  
networks:
  codegram-net: 
    driver: bridge

volumes:
  mysql-data:
